/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClasificacionDePizzasSauceClassificationBox.java
 *
 * Created on 11-ene-2010, 17:51:37
 */
package clasificaciondepizzas;

import clasificaciondepizzas.chart.SauceChart;
import clasificaciondepizzas.classification.EvaluatorSauce;
import org.jfree.chart.ChartPanel;

/**
 *
 * @author Manuel
 */
public class ClasificacionDePizzasSauceClassificationBox extends javax.swing.JDialog {

    /** Creates new form ClasificacionDePizzasSauceClassificationBox */
    public ClasificacionDePizzasSauceClassificationBox(java.awt.Frame parent, double meanH, double standardDeviationH, double meanS, double standardDeviationS) {
        super(parent);
        this.meanH = meanH;
        this.standardDeviationH = standardDeviationH;
        this.meanS = meanS;
        this.standardDeviationS = standardDeviationS;
        initComponents();
        showChart();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chartInternalFrame = new javax.swing.JInternalFrame();
        meanHWeightLabel = new javax.swing.JLabel();
        meanHWeightComboBox = new javax.swing.JComboBox();
        standardDeviationHLabel = new javax.swing.JLabel();
        standardDeviationHWeightComboBox = new javax.swing.JComboBox();
        meanSWeightLabel = new javax.swing.JLabel();
        meanSWeightComboBox = new javax.swing.JComboBox();
        standardDeviationSLabel = new javax.swing.JLabel();
        standardDeviationSWeightComboBox = new javax.swing.JComboBox();
        sauceTypeLabel = new javax.swing.JLabel();
        appSauceTypeLabel = new javax.swing.JLabel();
        classifyButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        chartInternalFrame.setName("chartInternalFrame"); // NOI18N
        chartInternalFrame.setVisible(true);

        javax.swing.GroupLayout chartInternalFrameLayout = new javax.swing.GroupLayout(chartInternalFrame.getContentPane());
        chartInternalFrame.getContentPane().setLayout(chartInternalFrameLayout);
        chartInternalFrameLayout.setHorizontalGroup(
            chartInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
        );
        chartInternalFrameLayout.setVerticalGroup(
            chartInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(clasificaciondepizzas.ClasificacionDePizzasApp.class).getContext().getResourceMap(ClasificacionDePizzasSauceClassificationBox.class);
        meanHWeightLabel.setText(resourceMap.getString("meanHWeightLabel.text")); // NOI18N
        meanHWeightLabel.setName("meanHWeightLabel"); // NOI18N

        meanHWeightComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        meanHWeightComboBox.setName("meanHWeightComboBox"); // NOI18N

        standardDeviationHLabel.setText(resourceMap.getString("standardDeviationHLabel.text")); // NOI18N
        standardDeviationHLabel.setName("standardDeviationHLabel"); // NOI18N

        standardDeviationHWeightComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        standardDeviationHWeightComboBox.setName("standardDeviationHWeightComboBox"); // NOI18N

        meanSWeightLabel.setText(resourceMap.getString("meanSWeightLabel.text")); // NOI18N
        meanSWeightLabel.setName("meanSWeightLabel"); // NOI18N

        meanSWeightComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        meanSWeightComboBox.setName("meanSWeightComboBox"); // NOI18N

        standardDeviationSLabel.setText(resourceMap.getString("standardDeviationSLabel.text")); // NOI18N
        standardDeviationSLabel.setName("standardDeviationSLabel"); // NOI18N

        standardDeviationSWeightComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        standardDeviationSWeightComboBox.setName("standardDeviationSWeightComboBox"); // NOI18N

        sauceTypeLabel.setText(resourceMap.getString("sauceTypeLabel.text")); // NOI18N
        sauceTypeLabel.setName("sauceTypeLabel"); // NOI18N

        appSauceTypeLabel.setText(resourceMap.getString("appSauceTypeLabel.text")); // NOI18N
        appSauceTypeLabel.setName("appSauceTypeLabel"); // NOI18N

        classifyButton.setText(resourceMap.getString("classifyButton.text")); // NOI18N
        classifyButton.setName("classifyButton"); // NOI18N
        classifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classifyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chartInternalFrame)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sauceTypeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(appSauceTypeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 279, Short.MAX_VALUE)
                        .addComponent(classifyButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(meanHWeightLabel)
                            .addComponent(meanHWeightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(standardDeviationHLabel)
                            .addComponent(standardDeviationHWeightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(meanSWeightLabel)
                            .addComponent(meanSWeightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(standardDeviationSWeightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(standardDeviationSLabel))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chartInternalFrame)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(meanHWeightLabel)
                    .addComponent(standardDeviationHLabel)
                    .addComponent(meanSWeightLabel)
                    .addComponent(standardDeviationSLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(meanHWeightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(standardDeviationHWeightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(meanSWeightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(standardDeviationSWeightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sauceTypeLabel)
                            .addComponent(appSauceTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(classifyButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void classifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classifyButtonActionPerformed
        EvaluatorSauce es = new EvaluatorSauce(meanHWeightComboBox.getSelectedIndex() + 1, standardDeviationHWeightComboBox.getSelectedIndex() + 1, meanSWeightComboBox.getSelectedIndex() + 1, standardDeviationSWeightComboBox.getSelectedIndex() + 1);
        String sauceType = es.pizzaCalculate(meanH, standardDeviationH, meanS, standardDeviationS);
        appSauceTypeLabel.setText(sauceType);
    }//GEN-LAST:event_classifyButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appSauceTypeLabel;
    private javax.swing.JInternalFrame chartInternalFrame;
    private javax.swing.JButton classifyButton;
    private javax.swing.JComboBox meanHWeightComboBox;
    private javax.swing.JLabel meanHWeightLabel;
    private javax.swing.JComboBox meanSWeightComboBox;
    private javax.swing.JLabel meanSWeightLabel;
    private javax.swing.JLabel sauceTypeLabel;
    private javax.swing.JLabel standardDeviationHLabel;
    private javax.swing.JComboBox standardDeviationHWeightComboBox;
    private javax.swing.JLabel standardDeviationSLabel;
    private javax.swing.JComboBox standardDeviationSWeightComboBox;
    // End of variables declaration//GEN-END:variables
    private double meanH;
    private double standardDeviationH;
    private double meanS;
    private double standardDeviationS;

    public void showChart() {
        EvaluatorSauce es = new EvaluatorSauce(meanHWeightComboBox.getSelectedIndex() + 1, standardDeviationHWeightComboBox.getSelectedIndex() + 1, meanSWeightComboBox.getSelectedIndex() + 1, standardDeviationSWeightComboBox.getSelectedIndex() + 1);
        String sauceType = es.pizzaCalculate(meanH, standardDeviationH, meanS, standardDeviationS);
        appSauceTypeLabel.setText(sauceType);
        SauceChart sauce = new SauceChart(meanH, standardDeviationH, meanS, standardDeviationS);
        ChartPanel bpanel = new ChartPanel(sauce.getChart());
        bpanel.setVisible(true);
        chartInternalFrame.setContentPane(bpanel);
    }
}
